server:
  port: 8091

fint:
  springer:
    clean-on-startup: true

  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
    organizations: fintlabs.no

  oauth:
    enabled: false
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client
